# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: postgres
    password: 12345678

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZjI5ZTE5MGM0MzA5MGE3OTJjNmUzYWZkMzQ4YzdlYjIyMWFjZTA5MzhkYzliNWYyMzZkMzYxYTQ0NjA3OGIzNTllNmQzOGE2ODdlN2VmYTQ5ZDlkYmIwYTM1NTEwMmNiMWVkNzIwMzNmNWEzZmM0NDZmNzBkODM5YzkxM2U3MDM=
